#!/bin/dash

#
# PowerPrompt
#

# Dmenu Prompts for power options

options="No\nSleep\nHibernate\nPower\nReboot"

selection=$(echo "$options" | dmenu -i -p "Power?")

case "$selection" in
    No) return ;;
    Sleep) loginctl suspend ;;
    Hibernate) loginctl hibernate ;;
    Power) sudo poweroff ;;
    Reboot) sudo reboot ;;
esac
