#!/bin/dash

#
# XftDpi
#

# Check Xft.xpi, if numerical argument is within range, change "Xft.dpi: " value in ~/.Xresources and update xrdb

if [ $# -eq 0 ] ; then
    xrdb -query | grep Xft.dpi
    exit 0
fi

case "$1" in
    # 70-259
    [:7-9:][:0-9:]|1[:0-9:][:0-9:]|2[:0-5:][:0-9:])
	sed -i "s/Xft.dpi.*/Xft.dpi: $1/g" $HOME/.Xresources &&
	echo "Xft.dpi $1" ;;
    *) echo "doing nothing" ;;
esac

xrdb $HOME/.Xresources
